// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { useCallback, useEffect, useState } from "react";
import { unified } from "https://esm.sh/unified@11.0.5";
import remarkParse from "https://esm.sh/remark-parse@11.0.0";
import remarkGfm from "https://esm.sh/remark-gfm@4.0.0";
import remarkRehype from "https://esm.sh/remark-rehype@11.1.1";
import rehypeStringify from "https://esm.sh/rehype-stringify@10.0.1";
import { Gamepad2, AlertTriangle, FileText } from "lucide-react";

const theme = {
  bg: "#0d0e0f",
  fg: "#f2eee2",
  card: "#1a1916",
  border: "#2c2a24",
  muted: "#a39c8a",
  accent: "#ffc400",
  caution: "#ff6b5e",
};

export default function ParkwiseReport() {
  const [html, setHtml] = useState("");
  const [err, setErr] = useState(false);

  const compile = useCallback(async () => {
    try {
      const res = await fetch("/api/parkwise-report", {
        headers: { Accept: "application/json" },
      });
      if (!res.ok) throw new Error("fetch failed");
      const data = await res.json();
      const file = await unified()
        .use(remarkParse)
        .use(remarkGfm)
        .use(remarkRehype)
        .use(rehypeStringify)
        .process(data.markdown || "");
      setHtml(String(file));
      setErr(false);
    } catch (e) {
      setErr(true);
    }
  }, []);

  useEffect(() => {
    compile();
  }, [compile]);

  return (
    <main
      style={
        {
          "--bg": theme.bg,
          "--fg": theme.fg,
          "--card": theme.card,
          "--border": theme.border,
          "--muted": theme.muted,
          "--accent": theme.accent,
          "--caution": theme.caution,
        } as React.CSSProperties
      }
      className="min-h-screen bg-[var(--bg)] text-[var(--fg)]"
    >
      <div className="mx-auto max-w-3xl px-4 py-10 sm:px-6">
        <style>{`
          @import url('https://fonts.googleapis.com/css2?family=Anton&family=IBM+Plex+Mono:wght@400;600&display=swap');
          .prose-pw { line-height: 1.75; font-size: 1.02rem; color: var(--fg); overflow-wrap: break-word; }
          .prose-pw h1 { font-family: 'Anton', sans-serif; font-size: 2.2rem; font-weight: 800; letter-spacing: 0.01em; line-height: 1.12; margin: 0 0 .5rem; text-transform: uppercase; }
          .prose-pw h2 { font-size: 1.4rem; font-weight: 700; margin: 2.4rem 0 .8rem; padding-top: 1.2rem; border-top: 1px solid var(--border); color: var(--accent); }
          .prose-pw h3 { font-size: 1.12rem; font-weight: 600; margin: 1.8rem 0 .5rem; color: var(--fg); }
          .prose-pw p { margin: .85rem 0; }
          .prose-pw ul, .prose-pw ol { margin: .85rem 0; padding-left: 1.4rem; }
          .prose-pw ul { list-style: disc; } .prose-pw ol { list-style: decimal; }
          .prose-pw li { margin: .35rem 0; }
          .prose-pw blockquote { border-left: 3px solid var(--accent); padding: .4rem 1.1rem; margin: 1.2rem 0; color: var(--muted); background: var(--card); border-radius: 0 .6rem .6rem 0; }
          .prose-pw a { color: var(--accent); text-decoration: underline; text-underline-offset: 2px; }
          .prose-pw strong { color: var(--fg); font-weight: 700; }
          .prose-pw em { color: var(--muted); }
          .prose-pw code { font-family: 'IBM Plex Mono', ui-monospace, monospace; font-size: .86em; background: var(--card); border: 1px solid var(--border); border-radius: .3rem; padding: 0 .3rem; color: var(--accent); }
          .prose-pw table { width: 100%; border-collapse: collapse; margin: 1.2rem 0; font-size: .88rem; }
          .prose-pw th, .prose-pw td { border: 1px solid var(--border); padding: .5rem .7rem; text-align: left; vertical-align: top; }
          .prose-pw th { background: var(--card); color: var(--accent); font-weight: 600; }
          .prose-pw hr { border: none; border-top: 1px solid var(--border); margin: 2.4rem 0; }
          .prose-pw section[data-footnotes] { margin-top: 2.5rem; padding-top: 1rem; border-top: 1px solid var(--border); font-size: .84rem; color: var(--muted); }
          .prose-pw section[data-footnotes] ol { padding-left: 1.1rem; list-style: decimal; }
          .prose-pw section[data-footnotes] li { margin: .45rem 0; }
        `}</style>

        <div className="mb-8 flex flex-col gap-4 border-b border-[var(--border)] pb-6 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-center gap-2 font-mono text-xs uppercase tracking-widest text-[var(--muted)]">
            <FileText className="size-4 text-[var(--accent)]" /> Kaarana ×
            CashlessConsumer · Report
          </div>
          <div className="flex gap-2">
            <a
              href="/parkwise-game"
              className="inline-flex items-center gap-1.5 rounded-lg bg-[var(--accent)] px-3 py-1.5 text-xs font-bold uppercase tracking-wide text-black transition-opacity hover:opacity-85"
            >
              <Gamepad2 className="size-3.5" /> Play the game
            </a>
            <a
              href="/parkwise-demo"
              className="inline-flex items-center gap-1.5 rounded-lg border border-[var(--border)] px-3 py-1.5 text-xs font-medium text-[var(--muted)] transition-colors hover:border-[var(--accent)] hover:text-[var(--accent)]"
            >
              API simulator
            </a>
          </div>
        </div>

        {err ? (
          <div className="flex items-start gap-3 rounded-xl border border-[var(--caution)]/40 bg-[var(--card)] p-5 text-sm text-[var(--caution)]">
            <AlertTriangle className="mt-0.5 size-5 shrink-0" />
            <div>
              <p className="font-semibold">Could not load the report.</p>
              <p className="mt-1 text-[var(--muted)]">Try again shortly.</p>
            </div>
          </div>
        ) : html ? (
          <div
            className="prose-pw"
            dangerouslySetInnerHTML={{ __html: html }}
          />
        ) : (
          <div className="animate-pulse space-y-3">
            <div className="h-7 w-3/4 rounded bg-[var(--border)]/60" />
            <div className="h-4 w-full rounded bg-[var(--border)]/40" />
            <div className="h-4 w-5/6 rounded bg-[var(--border)]/40" />
          </div>
        )}

        <div className="mt-10 flex flex-col gap-2 border-t border-[var(--border)] pt-5 font-mono text-xs text-[var(--muted)]">
          <p>
            Kaarana · ಕಾರಣ — independent critique of Aadhaar &amp; Digital
            India · Sept 2026
          </p>
          <p>
            Fork the evidence bench: simulator · 5 harm pages · report · game —
            all from one API spec.
          </p>
        </div>
      </div>
    </main>
  );
}