// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { useEffect, useRef, useState, useCallback } from "react";
import * as THREE from "https://esm.sh/three@0.170.0";

/* ============ palette ============ */
const C = {
  bg: 0x0d0e0f,
  asphalt: 0x17181b,
  curb: 0x3a3d33,
  bldg: [0x23262b, 0x2a2530, 0x1f2a2e, 0x2b2320, 0x252d25],
  sign: 0xffc400,
  red: 0xff5340,
  green: 0x35d07f,
  blue: 0x4f9cf9,
  magenta: 0xd95ce8,
  carBody: 0xffc400,
};

const PLATE = "KA 05 MJ 4211";

/* ============ game data ============ */
type OrbSpec = { label: string; cat: keyof typeof CATCOLORS; ident?: boolean };
const CATCOLORS = { loc: C.sign, veh: C.red, con: C.blue, fin: C.green, beh: C.magenta };

interface DaySpec {
  title: string;
  narrative: string;
  forcedPay?: "app";
  payChoice?: boolean;
  extendChoice?: boolean;
  orbs: OrbSpec[];
  buyer: { name: string; buys: string; text: string; hit: string };
}

const DAYS: DaySpec[] = [
  {
    title: "MON · first park",
    narrative:
      "New week. The curb outside the district court is a smart zone now. Green bays, ₹40/hr, pay by app. It really is convenient. Park, pay, go to work.",
    forcedPay: "app",
    orbs: [
      { label: "geo 12.9612,77.5839", cat: "loc", ident: true },
      { label: "plate " + PLATE, cat: "veh", ident: true },
      { label: "vehicle class: LMV", cat: "veh" },
      { label: "phone +91 98•••", cat: "con", ident: true },
      { label: "arrival 09:41", cat: "beh" },
      { label: "UPI instrument", cat: "fin", ident: true },
    ],
    buyer: {
      name: "City Mobility Dashboard",
      buys: "occupancy feed",
      text: "Day one. The ULB dashboard turns green — bay occupied, fee received. The civic story works. Nobody in the control room sees the columns underneath.",
      hit: "occupancy analytics · public dashboards",
    },
  },
  {
    title: "TUE · the kiosk question",
    narrative:
      "Same curb. Today you notice the kiosk by the footpath. Cash inside the machine, no phone number asked. Or tap the app like everyone else.",
    payChoice: true,
    orbs: [],
    buyer: {
      name: "PayLittle Insurance",
      buys: "plate + zone + dwell time",
      text: 'A motor pilot prices your policy by curb: the bay sits 90 m from a bar (late-night claims cluster), so the zone carries a "night-risk" loading. Cash at the kiosk hides your phone — but your plate is public, and VAHAN + camera networks re-attach your name. Inference, not verdict: this is how the join works.',
      hit: "premium adjusted by parking geography",
    },
  },
  {
    title: "WED · plans change",
    narrative:
      "Hearing runs long. Extend an hour in the app — honest and easy. Or pull out and circle till the coast looks clear. Both leave marks.",
    extendChoice: true,
    orbs: [],
    buyer: {
      name: "ScreenWork HR Analytics",
      buys: "update events + dwell pattern",
      text: 'Extensions timestamp your plans. Circulating doesn\'t hide you: ANPR poles read the plate each lap and the movement model tags "evasive loitering". Either way a screening API learns this street is part of your week. It cannot learn why — and it doesn\'t ask.',
      hit: '"poor schedule discipline" score −12',
    },
  },
  {
    title: "THU · kiosk offline",
    narrative:
      "The kiosk shows a dead screen. A sticker says: UPI ONLY. The convenient option is now the only option. Park, pay, done.",
    forcedPay: "app",
    orbs: [
      { label: "geo 12.9612,77.5839", cat: "loc", ident: true },
      { label: "plate " + PLATE, cat: "veh", ident: true },
      { label: "phone +91 98•••", cat: "con", ident: true },
      { label: "email r•••@gmail", cat: "con", ident: true },
      { label: "device model", cat: "con", ident: true },
      { label: "arrival 09:38", cat: "beh" },
      { label: "extension +1 hr", cat: "beh" },
      { label: "departure 14:12", cat: "beh" },
      { label: "UPI instrument", cat: "fin", ident: true },
    ],
    buyer: {
      name: "WhereYouGo Brokers",
      buys: "full presence history",
      text: "A location broker merges the week: this street, Tue–Thu, 09:40 ± 3 min. Circuit-court adjacency + a public cause list + the plate's registered owner = a probable profession. Inference, labelled as inference. The broker has never met you and knows your Tuesday.",
      hit: "home-workplace graph · 4th data reseller",
    },
  },
  {
    title: "FRI · the cameras join",
    narrative:
      "Two new grey poles on the street. Plate readers, wired to the parking ledger. You don't have to park to be counted today — only to drive past.",
    forcedPay: "app",
    orbs: [
      { label: "plate @ pole-1", cat: "veh", ident: true },
      { label: "time @ pole-1", cat: "beh" },
      { label: "plate @ pole-2", cat: "veh", ident: true },
      { label: "time @ pole-2", cat: "beh" },
      { label: "geo + dwell", cat: "loc", ident: true },
      { label: "plate " + PLATE, cat: "veh", ident: true },
      { label: "UPI instrument", cat: "fin", ident: true },
      { label: "departure 13:05", cat: "beh" },
    ],
    buyer: {
      name: "Merged file: insurer × broker × ANPR",
      buys: "everything",
      text: 'Five days, one curb. The merged file carries a "presence score" — risk quotient of a person assembled from where a car stood. The court employee parking near a court is now a flagged pattern. The system never decided anything about you. It didn\'t have to. It just sold the columns.',
      hit: "presence score 7.3/10 · quoted to a lender",
    },
  },
];

/* ============ helpers ============ */
function makeTextSprite(text: string, color: string, scale = 1): THREE.Sprite {
  const cvs = document.createElement("canvas");
  cvs.width = 256;
  cvs.height = 64;
  const ctx = cvs.getContext("2d")!;
  ctx.fillStyle = "rgba(10,10,12,0.85)";
  ctx.fillRect(0, 0, 256, 64);
  ctx.strokeStyle = color;
  ctx.lineWidth = 3;
  ctx.strokeRect(1.5, 1.5, 253, 61);
  ctx.font = "600 26px 'IBM Plex Mono', monospace";
  ctx.fillStyle = color;
  ctx.textAlign = "center";
  ctx.textBaseline = "middle";
  ctx.fillText(text.slice(0, 22), 128, 34);
  const tex = new THREE.CanvasTexture(cvs);
  const mat = new THREE.SpriteMaterial({ map: tex, transparent: true, depthTest: false });
  const spr = new THREE.Sprite(mat);
  spr.scale.set(2.6 * scale, 0.65 * scale, 1);
  return spr;
}

function makePlateTexture(): THREE.CanvasTexture {
  const cvs = document.createElement("canvas");
  cvs.width = 256;
  cvs.height = 64;
  const ctx = cvs.getContext("2d")!;
  ctx.fillStyle = "#f4f1e6";
  ctx.fillRect(0, 0, 256, 64);
  ctx.strokeStyle = "#111";
  ctx.lineWidth = 4;
  ctx.strokeRect(2, 2, 252, 60);
  ctx.font = "700 34px 'IBM Plex Mono', monospace";
  ctx.fillStyle = "#111";
  ctx.textAlign = "center";
  ctx.textBaseline = "middle";
  ctx.fillText(PLATE, 128, 34);
  return new THREE.CanvasTexture(cvs);
}

/* ============ engine ============ */
interface EngineState {
  phase: "intro" | "driving" | "paying" | "collecting" | "buyer" | "receipt";
  day: number;
  points: number;
  identifying: number;
  catCounts: Record<string, number>;
  holdPct: number;
  circled: boolean;
  cashChoice: boolean | null;
  extendChoice: boolean | null;
  anprReads: number;
  surveillance: boolean;
  toast: string | null;
  parkHint: string | null;
}

function buildEngine(
  mount: HTMLDivElement,
  ui: (s: Partial<EngineState>) => void
) {
  const W = () => mount.clientWidth;
  const H = () => mount.clientHeight;

  const scene = new THREE.Scene();
  scene.background = new THREE.Color(C.bg);
  scene.fog = new THREE.Fog(C.bg, 60, 160);

  const camera = new THREE.PerspectiveCamera(58, W() / H(), 0.1, 400);
  const renderer = new THREE.WebGLRenderer({ antialias: true });
  renderer.setSize(W(), H());
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  mount.appendChild(renderer.domElement);

  const hemi = new THREE.HemisphereLight(0xcfd6de, 0x1a1c20, 0.9);
  scene.add(hemi);
  const sun = new THREE.DirectionalLight(0xfff2d0, 1.6);
  sun.position.set(30, 50, 20);
  scene.add(sun);

  /* ---- city ---- */
  const city = new THREE.Group();
  scene.add(city);

  const ground = new THREE.Mesh(
    new THREE.PlaneGeometry(240, 240),
    new THREE.MeshStandardMaterial({ color: C.asphalt, roughness: 1 })
  );
  ground.rotation.x = -Math.PI / 2;
  city.add(ground);

  // road: z axis street, x from -7..7
  const roadMat = new THREE.MeshStandardMaterial({ color: 0x101114, roughness: 0.95 });
  const road = new THREE.Mesh(new THREE.PlaneGeometry(16, 240), roadMat);
  road.rotation.x = -Math.PI / 2;
  road.position.y = 0.01;
  city.add(road);

  // dashed center line
  const lineMat = new THREE.MeshBasicMaterial({ color: 0x8a8455 });
  for (let z = -110; z < 110; z += 6) {
    const dash = new THREE.Mesh(new THREE.PlaneGeometry(0.25, 2.6), lineMat);
    dash.rotation.x = -Math.PI / 2;
    dash.position.set(0, 0.02, z);
    city.add(dash);
  }

  // buildings both sides
  const bldgBoxes: { min: THREE.Vector2; max: THREE.Vector2 }[] = [];
  let seed = 7;
  const rnd = () => {
    seed = (seed * 16807) % 2147483647;
    return seed / 2147483647;
  };
  const bldgMats: THREE.MeshStandardMaterial[] = [];
  for (const side of [-1, 1]) {
    let z = -110;
    while (z < 110) {
      const w = 10 + rnd() * 12;
      const d = 10 + rnd() * 14;
      const h = 6 + rnd() * 22;
      const mat = new THREE.MeshStandardMaterial({
        color: C.bldg[Math.floor(rnd() * C.bldg.length)],
        roughness: 0.9,
      });
      bldgMats.push(mat);
      const b = new THREE.Mesh(new THREE.BoxGeometry(w, h, d), mat);
      b.position.set(side * (9 + w / 2 + rnd() * 4), h / 2, z + d / 2);
      city.add(b);
      bldgBoxes.push({
        min: new THREE.Vector2(b.position.x - w / 2, b.position.z - d / 2),
        max: new THREE.Vector2(b.position.x + w / 2, b.position.z + d / 2),
      });
      z += d + 1.5 + rnd() * 3;
    }
  }

  // parking bays along right curb x∈[6.2..8.8], z∈[-14..+14]
  const bays: { z: number; mesh: THREE.Mesh; hl: THREE.Mesh | null; occupied: boolean }[] = [];
  const bayGeo = new THREE.PlaneGeometry(2.6, 5.4);
  const bayLineMat = new THREE.MeshBasicMaterial({ color: 0xe8e4d0 });
  for (let i = 0; i < 6; i++) {
    const z = -11 + i * 4.6;
    const m = new THREE.Mesh(bayGeo, bayLineMat);
    m.rotation.x = -Math.PI / 2;
    m.rotation.z = Math.PI / 2;
    m.position.set(7.4, 0.03, z);
    city.add(m);
    bays.push({ z, mesh: m, hl: null, occupied: false });
  }
  // occupied bays: static cars
  const otherCarColors = [0x5b6770, 0x7a4a45, 0x46586a, 0x6a6247];
  bays[0].occupied = true;
  bays[3].occupied = true;
  bays[5].occupied = true;
  [0, 3, 5].forEach((bi, i) => {
    const c = new THREE.Mesh(
      new THREE.BoxGeometry(1.8, 1.1, 4.2),
      new THREE.MeshStandardMaterial({ color: otherCarColors[i], roughness: 0.6 })
    );
    c.position.set(7.4, 0.55, bays[bi].z);
    city.add(c);
  });

  // highlight bay for current day (target = first free bay)
  const hlMat = new THREE.MeshBasicMaterial({
    color: C.sign,
    transparent: true,
    opacity: 0.35,
    side: THREE.DoubleSide,
  });
  const targetBay = bays[1];
  const hl = new THREE.Mesh(bayGeo, hlMat);
  hl.rotation.x = -Math.PI / 2;
  hl.rotation.z = Math.PI / 2;
  hl.position.set(7.4, 0.04, targetBay.z);
  city.add(hl);
  // sign post
  const signPost = new THREE.Group();
  const pole = new THREE.Mesh(
    new THREE.CylinderGeometry(0.07, 0.07, 3, 8),
    new THREE.MeshStandardMaterial({ color: 0x555a60 })
  );
  pole.position.y = 1.5;
  signPost.add(pole);
  const signCvs = document.createElement("canvas");
  signCvs.width = 128;
  signCvs.height = 128;
  const sctx = signCvs.getContext("2d")!;
  sctx.fillStyle = "#1b3a8a";
  sctx.fillRect(0, 0, 128, 128);
  sctx.fillStyle = "#fff";
  sctx.font = "700 72px sans-serif";
  sctx.textAlign = "center";
  sctx.fillText("P", 64, 78);
  sctx.font = "600 22px sans-serif";
  sctx.fillText("₹40/hr", 64, 110);
  const sign = new THREE.Mesh(
    new THREE.PlaneGeometry(1.2, 1.2),
    new THREE.MeshStandardMaterial({ map: new THREE.CanvasTexture(signCvs), side: THREE.DoubleSide })
  );
  sign.position.y = 3.1;
  signPost.add(sign);
  signPost.position.set(9.1, 0, targetBay.z + 3);
  city.add(signPost);

  // ANPR poles
  const anprPoles: { z: number; read: boolean; cone: THREE.Mesh }[] = [];
  for (const pz of [-24, 22]) {
    const g = new THREE.Group();
    const p = new THREE.Mesh(
      new THREE.CylinderGeometry(0.09, 0.09, 5, 8),
      new THREE.MeshStandardMaterial({ color: 0x3d4147 })
    );
    p.position.y = 2.5;
    g.add(p);
    const cam = new THREE.Mesh(
      new THREE.BoxGeometry(0.5, 0.25, 0.25),
      new THREE.MeshStandardMaterial({ color: 0x22252a })
    );
    cam.position.set(-0.5, 4.8, 0);
    g.add(cam);
    const cone = new THREE.Mesh(
      new THREE.ConeGeometry(3.2, 8, 16, 1, true),
      new THREE.MeshBasicMaterial({ color: C.red, transparent: true, opacity: 0.1, side: THREE.DoubleSide })
    );
    cone.rotation.z = Math.PI / 2;
    cone.position.set(-4.4, 4.4, 0);
    g.add(cone);
    g.position.set(8.5, 0, pz);
    city.add(g);
    anprPoles.push({ z: pz, read: false, cone });
  }

  // data tower
  const tower = new THREE.Group();
  const tm = new THREE.MeshStandardMaterial({ color: 0x4a4f57, roughness: 0.5, metalness: 0.4 });
  const t1 = new THREE.Mesh(new THREE.CylinderGeometry(0.25, 0.6, 26, 10), tm);
  t1.position.y = 13;
  tower.add(t1);
  for (const [dy, w] of [
    [22, 3.4],
    [19, 2.6],
    [16, 2],
  ] as const) {
    const dish = new THREE.Mesh(new THREE.BoxGeometry(w, 0.3, 0.7), tm);
    dish.position.y = dy;
    tower.add(dish);
  }
  const beacon = new THREE.Mesh(
    new THREE.SphereGeometry(0.3, 12, 12),
    new THREE.MeshBasicMaterial({ color: C.red })
  );
  beacon.position.y = 26.4;
  tower.add(beacon);
  tower.position.set(-26, 0, 6);
  city.add(tower);
  const towerTop = new THREE.Vector3(-26, 23, 6);

  // pulsing ring
  const ring = new THREE.Mesh(
    new THREE.TorusGeometry(1, 0.05, 8, 40),
    new THREE.MeshBasicMaterial({ color: C.sign, transparent: true })
  );
  ring.rotation.x = Math.PI / 2;
  ring.position.set(-26, 0.1, 6);
  city.add(ring);

  // pedestrians
  const peds: { mesh: THREE.Mesh; z: number; dir: number; speed: number }[] = [];
  for (const [x, z, dir] of [
    [-9.5, 20, -1],
    [9.8, -30, 1],
  ] as const) {
    const ped = new THREE.Mesh(
      new THREE.CapsuleGeometry(0.28, 0.9, 4, 8),
      new THREE.MeshStandardMaterial({ color: 0x8d8478 })
    );
    ped.position.set(x, 0.75, z);
    city.add(ped);
    peds.push({ mesh: ped, z, dir, speed: 1.2 });
  }

  /* ---- car ---- */
  const car = new THREE.Group();
  const body = new THREE.Mesh(
    new THREE.BoxGeometry(1.9, 0.75, 4.2),
    new THREE.MeshStandardMaterial({ color: C.carBody, roughness: 0.35, metalness: 0.2 })
  );
  body.position.y = 0.55;
  car.add(body);
  const cabin = new THREE.Mesh(
    new THREE.BoxGeometry(1.7, 0.6, 2.2),
    new THREE.MeshStandardMaterial({ color: 0x1c1e22, roughness: 0.2, metalness: 0.5 })
  );
  cabin.position.set(0, 1.2, -0.2);
  car.add(cabin);
  const wheelGeo = new THREE.CylinderGeometry(0.34, 0.34, 0.25, 12);
  const wheelMat = new THREE.MeshStandardMaterial({ color: 0x0c0d0f, roughness: 0.9 });
  for (const [wx, wz] of [
    [0.95, 1.4],
    [0.95, -1.4],
    [-0.95, 1.4],
    [-0.95, -1.4],
  ] as const) {
    const w = new THREE.Mesh(wheelGeo, wheelMat);
    w.rotation.x = Math.PI / 2;
    w.position.set(wx, 0.34, wz);
    car.add(w);
  }
  const plateTex = makePlateTexture();
  const plateMat = new THREE.MeshBasicMaterial({ map: plateTex });
  for (const [pz, ry] of [
    [2.11, 0],
    [-2.11, Math.PI],
  ] as const) {
    const pl = new THREE.Mesh(new THREE.PlaneGeometry(0.85, 0.22), plateMat);
    pl.position.set(0, 0.5, pz);
    pl.rotation.y = ry;
    car.add(pl);
  }
  scene.add(car);

  /* ---- trail ---- */
  const trailPts: THREE.Vector3[] = [];
  const trailGeo = new THREE.BufferGeometry();
  const trailLine = new THREE.Line(
    trailGeo,
    new THREE.LineBasicMaterial({ color: C.sign, transparent: true, opacity: 0.55 })
  );
  trailLine.visible = false;
  scene.add(trailLine);

  /* ---- orbs ---- */
  const orbs: { spr: THREE.Sprite; label: THREE.Sprite; t: number; from: THREE.Vector3 }[] = [];
  function spawnOrb(spec: OrbSpec) {
    const col = "#" + new THREE.Color(CATCOLORS[spec.cat]).getHexString();
    const orb = new THREE.Sprite(
      new THREE.SpriteMaterial({ color: CATCOLORS[spec.cat], transparent: true, depthTest: false })
    );
    orb.scale.set(0.34, 0.34, 1);
    const from = car.position.clone().add(new THREE.Vector3(0, 1.4, 0));
    orb.position.copy(from);
    const label = makeTextSprite(spec.label, col, 0.85);
    label.position.copy(from).add(new THREE.Vector3(0, 0.5, 0));
    scene.add(orb);
    scene.add(label);
    orbs.push({ spr: orb, label, t: 0, from });
  }

  /* ---- state ---- */
  const st: EngineState = {
    phase: "intro",
    day: 0,
    points: 0,
    identifying: 0,
    catCounts: {},
    holdPct: 0,
    circled: false,
    cashChoice: null,
    extendChoice: null,
    anprReads: 0,
    surveillance: false,
    toast: null,
    parkHint: null,
  };
  const push = () => ui({ ...st });

  const keys: Record<string, boolean> = {};
  const onKeyDown = (e: KeyboardEvent) => {
    const k = e.key.toLowerCase();
    if (["arrowup", "arrowdown", "arrowleft", "arrowright", " "].includes(k)) e.preventDefault();
    keys[k] = true;
    if (k === "tab") {
      e.preventDefault();
      toggleView();
    }
    if (k === "r" && st.phase === "driving") respawn();
  };
  const onKeyUp = (e: KeyboardEvent) => {
    keys[e.key.toLowerCase()] = false;
  };
  window.addEventListener("keydown", onKeyDown);
  window.addEventListener("keyup", onKeyUp);

  /* ---- car physics ---- */
  const pos = new THREE.Vector3(0, 0, -60);
  let heading = 0; // 0 => +z
  let speed = 0;
  function respawn() {
    pos.set(0, 0, -60);
    heading = 0;
    speed = 0;
  }

  function toggleView() {
    st.surveillance = !st.surveillance;
    trailLine.visible = st.surveillance;
    anprPoles.forEach((p) => (p.cone.visible = st.surveillance));
    bldgMats.forEach((m) => {
      m.wireframe = st.surveillance;
    });
    scene.background = new THREE.Color(st.surveillance ? 0x07080a : C.bg);
    scene.fog!.color = new THREE.Color(st.surveillance ? 0x07080a : C.bg);
    sun.intensity = st.surveillance ? 0.5 : 1.6;
    push();
  }

  /* ---- day flow ---- */
  function startGame() {
    st.phase = "driving";
    st.day = 0;
    push();
  }

  function startDay(dayIdx: number) {
    st.day = dayIdx;
    st.phase = "driving";
    st.holdPct = 0;
    parkedDone = false;
    st.parkHint = null;
    respawn();
    trailPts.length = 0;
    anprPoles.forEach((p) => (p.read = false));
    push();
  }

  function doCollection() {
    st.phase = "collecting";
    const day = DAYS[st.day];
    let specs: OrbSpec[] = [];
    if (st.day === 1) {
      specs = st.cashChoice
        ? [
            { label: "plate " + PLATE, cat: "veh", ident: true },
            { label: "geo + arrival", cat: "loc", ident: true },
            { label: "cash, no id", cat: "fin" },
            { label: "dwell 3h10m", cat: "beh" },
          ]
        : [
            { label: "plate " + PLATE, cat: "veh", ident: true },
            { label: "geo 12.9612,77.5839", cat: "loc", ident: true },
            { label: "phone +91 98•••", cat: "con", ident: true },
            { label: "UPI instrument", cat: "fin", ident: true },
            { label: "dwell 3h10m", cat: "beh" },
            { label: "arrival 09:44", cat: "beh" },
          ];
    } else if (st.day === 2) {
      specs = st.extendChoice
        ? [
            { label: "extension +1 hr", cat: "beh" },
            { label: "new end time", cat: "beh" },
            { label: "plan-change signal", cat: "beh", ident: true },
          ]
        : [
            { label: "ANPR lap read ×3", cat: "veh", ident: true },
            { label: "evasive loiter flag", cat: "beh", ident: true },
            { label: "lap trajectory", cat: "loc", ident: true },
          ];
    } else {
      specs = day.orbs;
    }
    specs.forEach((s, i) => {
      setTimeout(() => {
        spawnOrb(s);
      }, i * 420);
    });
    const total = specs.length * 420 + 1700;
    setTimeout(() => {
      st.phase = "buyer";
      push();
    }, total);
  }

  function nextDay() {
    if (st.day + 1 >= DAYS.length) {
      st.phase = "receipt";
      push();
    } else {
      startDay(st.day + 1);
    }
  }

  /* ---- per-frame ---- */
  const clock = new THREE.Clock();
  let trailTimer = 0;
  let parkedDone = false;
  const camTarget = new THREE.Vector3();
  let raf = 0;

  function tick() {
    raf = requestAnimationFrame(tick);
    const dt = Math.min(clock.getDelta(), 0.05);
    const t = clock.elapsedTime;

    // pedestrians
    peds.forEach((p) => {
      p.z += p.dir * p.speed * dt;
      if (p.z > 60) p.dir = -1;
      if (p.z < -60) p.dir = 1;
      p.mesh.position.z = p.z;
      p.mesh.rotation.z = Math.sin(t * 6 + p.z) * 0.06;
    });

    // beacon + ring pulse
    (beacon.material as THREE.MeshBasicMaterial).color.setHex(Math.sin(t * 4) > 0 ? C.red : 0x551512);
    const rs = 1 + ((t * 2.2) % 3);
    ring.scale.set(rs, rs, 1);
    (ring.material as THREE.MeshBasicMaterial).opacity = Math.max(0, 1 - rs / 3);

    // driving physics
    if (st.phase === "driving") {
      const accel = keys["w"] || keys["arrowup"] ? 9 : 0;
      const brake = keys["s"] || keys["arrowdown"] ? 12 : 0;
      const steer = (keys["a"] || keys["arrowleft"] ? 1 : 0) - (keys["d"] || keys["arrowright"] ? 1 : 0);
      speed += (accel - brake) * dt;
      speed *= 1 - 0.6 * dt;
      speed = THREE.MathUtils.clamp(speed, -5, 15);
      heading += steer * 1.9 * dt * Math.min(1, 0.45 + Math.abs(speed) / 4) * Math.sign(speed || 1);
      const nx = pos.x + Math.sin(heading) * speed * dt;
      const nz = pos.z + Math.cos(heading) * speed * dt;
      // building collision
      let blocked = false;
      for (const b of bldgBoxes) {
        if (nx > b.min.x - 1.2 && nx < b.max.x + 1.2 && nz > b.min.y - 1.2 && nz < b.max.y + 1.2) {
          blocked = true;
          break;
        }
      }
      if (!blocked) {
        pos.x = THREE.MathUtils.clamp(nx, -60, 60);
        pos.z = THREE.MathUtils.clamp(nz, -110, 110);
      } else {
        speed *= -0.25;
      }
      car.position.copy(pos);
      car.rotation.y = heading;
      car.rotation.z = THREE.MathUtils.lerp(car.rotation.z, -steer * 0.04, 0.1);

      // trail
      trailTimer += dt;
      if (trailTimer > 0.14) {
        trailTimer = 0;
        trailPts.push(pos.clone());
        if (trailPts.length > 500) trailPts.shift();
        trailGeo.setFromPoints(trailPts);
      }

      // ANPR reads (day 5, or always in surveillance? keep day5 only)
      if (st.day === 4) {
        for (const p of anprPoles) {
          if (!p.read && Math.abs(pos.z - p.z) < 5 && pos.x > 3) {
            p.read = true;
            st.anprReads++;
            st.toast = "ANPR READ · " + PLATE + " · pole@" + p.z;
            push();
            setTimeout(() => {
              st.toast = null;
              push();
            }, 2600);
            spawnOrb({ label: "plate @ pole", cat: "veh", ident: true });
          }
        }
      }

      // park detection: bay1, x≈7.4, speed low, aligned
      const inBay = Math.abs(pos.x - 7.4) < 1.5 && Math.abs(pos.z - targetBay.z) < 2.6;
      const hNorm = Math.abs(((heading % Math.PI) + Math.PI) % Math.PI);
      const aligned = hNorm < 0.6 || Math.abs(hNorm - Math.PI) < 0.6;
      const offDeg = Math.round((Math.min(hNorm, Math.PI - hNorm) * 180) / Math.PI / 5) * 5;
      let hint: string | null = null;
      if (!parkedDone) {
        if (inBay && aligned && Math.abs(speed) >= 0.4) hint = "brake to a full stop";
        else if (inBay && !aligned) hint = "straighten along the curb · " + offDeg + "° off · nudge ▲/▼ while steering";
        else if (!inBay && Math.abs(pos.x - 7.4) < 3.4 && Math.abs(pos.z - targetBay.z) < 4.5) hint = "pull into the yellow bay";
        if (hint !== st.parkHint) { st.parkHint = hint; push(); }
      }
      if (inBay && Math.abs(speed) < 0.4 && aligned && !parkedDone) {
        st.holdPct = Math.min(1, st.holdPct + dt / 1.2);
        push();
        if (st.holdPct >= 1) {
          parkedDone = true;
          st.parkHint = null;
          const day = DAYS[st.day];
          if (day.payChoice) {
            st.phase = "paying";
          } else if (day.extendChoice) {
            st.phase = "paying";
          } else {
            doCollection();
          }
          push();
        }
      } else if (!parkedDone && st.holdPct > 0) {
        st.holdPct = Math.max(0, st.holdPct - dt * 0.8);
        push();
      }
    }

    // orbs flight
    for (let i = orbs.length - 1; i >= 0; i--) {
      const o = orbs[i];
      o.t += dt / 1.5;
      const e = o.t < 1 ? 1 - Math.pow(1 - o.t, 3) : 1;
      o.spr.position.lerpVectors(o.from, towerTop, e);
      o.spr.position.y += Math.sin(e * Math.PI) * 2.2;
      o.label.position.copy(o.spr.position).add(new THREE.Vector3(0, 0.55, 0));
      if (o.t >= 1) {
        scene.remove(o.spr);
        scene.remove(o.label);
        orbs.splice(i, 1);
        st.points++;
        st.catCounts["all"] = (st.catCounts["all"] || 0) + 1;
        push();
      }
    }

    // camera chase
    const fwd = new THREE.Vector3(Math.sin(heading), 0, Math.cos(heading));
    const desiredH = st.surveillance ? 15 : 6.2;
    const desiredB = st.surveillance ? 7 : 10.5;
    camTarget.copy(pos).addScaledVector(fwd, -desiredB).add(new THREE.Vector3(0, desiredH, 0));
    camera.position.lerp(camTarget, 1 - Math.pow(0.0015, dt));
    camera.lookAt(pos.clone().addScaledVector(fwd, 5).add(new THREE.Vector3(0, 1.2, 0)));

    renderer.render(scene, camera);
    raf = raf; // keep
  }
  tick();

  /* ---- choice handlers (called from React) ---- */
  function choosePay(cash: boolean) {
    st.cashChoice = cash;
    doCollection();
  }
  function chooseExtend(extend: boolean) {
    st.extendChoice = extend;
    doCollection();
  }
  function reset() {
    st.phase = "intro";
    st.day = 0;
    st.points = 0;
    st.identifying = 0;
    st.catCounts = {};
    st.holdPct = 0;
    st.circled = false;
    st.cashChoice = null;
    st.extendChoice = null;
    st.anprReads = 0;
    parkedDone = false;
    trailPts.length = 0;
    anprPoles.forEach((p) => (p.read = false));
    respawn();
    st.parkHint = null;
    push();
  }

  const onResize = () => {
    camera.aspect = W() / H();
    camera.updateProjectionMatrix();
    renderer.setSize(W(), H());
  };
  window.addEventListener("resize", onResize);

  return {
    startGame,
    choosePay,
    chooseExtend,
    nextDay,
    reset,
    toggleView,
    state: st,
    debugPark: (angle = 0) => {
      pos.set(7.4, 0, targetBay.z);
      heading = angle;
      speed = 0;
      parkedDone = false;
      car.position.copy(pos);
    },
    debugForcePark: () => {
      parkedDone = true;
      st.holdPct = 1;
      const d0 = DAYS[st.day];
      if (d0.payChoice || d0.extendChoice) {
        st.phase = "paying";
      } else {
        doCollection();
      }
      push();
    },
    setKey: (k: string, v: boolean) => {
      keys[k] = v;
    },
    dispose: () => {
      cancelAnimationFrame(raf);
      window.removeEventListener("keydown", onKeyDown);
      window.removeEventListener("keyup", onKeyUp);
      window.removeEventListener("resize", onResize);
      renderer.dispose();
      mount.innerHTML = "";
    },
  };
}

/* ============ react shell ============ */
type Phase = EngineState["phase"];

export default function ParkwiseGame() {
  const mountRef = useRef<HTMLDivElement>(null);
  const engineRef = useRef<ReturnType<typeof buildEngine> | null>(null);
  const [ui, setUi] = useState<Partial<EngineState>>({ phase: "intro", day: 0, points: 0, holdPct: 0, surveillance: false });

  useEffect(() => {
    if (!mountRef.current) return;
    const eng = buildEngine(mountRef.current, (s) => setUi((prev) => ({ ...prev, ...s })));
    engineRef.current = eng;
    (window as any).__pw = eng;
    return () => {
      eng.dispose();
      engineRef.current = null;
    };
  }, []);

  const eng = () => engineRef.current;
  const day = ui.day ?? 0;
  const daySpec = DAYS[Math.min(day, DAYS.length - 1)];

  const touch = (k: string) => ({
    onPointerDown: (e: React.PointerEvent) => {
      e.preventDefault();
      eng()?.setKey(k, true);
    },
    onPointerUp: () => eng()?.setKey(k, false),
    onPointerLeave: () => eng()?.setKey(k, false),
  });

  return (
    <div className="relative h-screen w-screen overflow-hidden bg-[#0d0e0f] font-mono text-[#f2eee2] select-none">
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Anton&family=IBM+Plex+Mono:wght@400;600;700&display=swap');
        .pw-canvas-mount canvas{display:block}
        .pw-btn{font-family:'IBM Plex Mono',monospace;border:1px solid #ffc400;color:#ffc400;padding:.55rem 1.1rem;font-size:12px;letter-spacing:.12em;text-transform:uppercase;transition:all .15s;background:transparent}
        .pw-btn:hover{background:#ffc400;color:#000}
        .pw-btn-solid{background:#ffc400;color:#000}
        .pw-btn-solid:hover{background:#ffd84d;border-color:#ffd84d}
        .pw-card{background:rgba(13,14,15,.94);border:1px solid #2c2a24;max-width:520px}
        .pw-tag{display:inline-block;padding:2px 8px;font-size:10px;letter-spacing:.14em;text-transform:uppercase;border:1px solid currentColor}`}</style>

      <div ref={mountRef} className="pw-canvas-mount absolute inset-0" />

      {/* HUD top bar */}
      {(ui.phase === "driving" || ui.phase === "collecting") && (
        <>
          <div className="pointer-events-none absolute left-4 top-4 z-10">
            <div className="pw-tag mb-2" style={{ color: "#ffc400" }}>
              day {day + 1}/5 · {daySpec.title}
            </div>
            <div className="max-w-xs text-[12px] leading-relaxed text-[#a39c8a]">
              {ui.phase === "driving"
                ? ui.holdPct && ui.holdPct > 0
                  ? `HOLD… ${Math.round((ui.holdPct || 0) * 100)}%`
                  : ui.parkHint
                    ? <span style={{ color: "#ffc400" }}>▸ {ui.parkHint}</span>
                    : "OBJECTIVE · park in the yellow bay"
                : "TRANSMITTING…"}
            </div>
          </div>
          <div className="pointer-events-none absolute right-4 top-4 z-10 text-right">
            <div className="text-3xl font-bold" style={{ color: "#ffc400" }}>
              {ui.points ?? 0}
            </div>
            <div className="text-[10px] uppercase tracking-[0.2em] text-[#a39c8a]">
              data points collected
            </div>
            <button
              className="pw-btn pointer-events-auto mt-3"
              onClick={() => eng()?.toggleView()}
            >
              {ui.surveillance ? "◀ convenience view" : "surveillance view ▶"} [tab]
            </button>
          </div>
          {ui.toast && (
            <div className="pointer-events-none absolute left-1/2 top-16 z-20 -translate-x-1/2 border px-4 py-2 text-xs font-bold uppercase tracking-widest"
              style={{ borderColor: "#ff5340", color: "#ff5340", background: "rgba(13,14,15,.9)" }}>
              {ui.toast}
            </div>
          )}
          {/* touch controls */}
          <div className="absolute inset-x-0 bottom-4 z-10 flex items-end justify-between px-5 sm:hidden">
            <div className="flex gap-3">
              <button className="pw-btn pw-btn-solid h-16 w-16 !px-0 text-lg" {...touch("a")}>◀</button>
              <button className="pw-btn pw-btn-solid h-16 w-16 !px-0 text-lg" {...touch("d")}>▶</button>
            </div>
            <div className="flex gap-3">
              <button className="pw-btn pw-btn-solid h-16 w-16 !px-0" {...touch("s")}>▼</button>
              <button className="pw-btn pw-btn-solid h-16 w-16 !px-0" {...touch("w")}>▲</button>
            </div>
          </div>
          <div className="absolute bottom-4 left-1/2 z-10 hidden -translate-x-1/2 text-[10px] uppercase tracking-[0.2em] text-[#a39c8a] sm:block">
            W A S D / arrows to drive · R reset car · TAB surveillance view
          </div>
        </>
      )}

      {/* INTRO */}
      {ui.phase === "intro" && (
        <div className="absolute inset-0 z-30 flex items-center justify-center bg-[#0d0e0f]/70 p-4">
          <div className="pw-card w-full p-8">
            <div className="pw-tag mb-4" style={{ color: "#ffc400" }}>
              kaarana × cashlessconsumer · [dpi] · a game
            </div>
            <h1 className="text-5xl uppercase leading-[0.95]" style={{ fontFamily: "Anton, sans-serif", color: "#f2eee2" }}>
              Pay &amp;<br />
              <span style={{ color: "#ffc400" }}>Display</span>
            </h1>
            <p className="mt-4 text-sm leading-relaxed text-[#a39c8a]">
              A parking game about what parking costs. Five days, one curb. Every session is real convenience — and a receipt you never see. Drive, park, pay, and watch the columns fill.
            </p>
            <ul className="mt-4 space-y-1 text-xs text-[#a39c8a]">
              <li>▸ W A S D / arrows — drive · TAB — surveillance view · R — reset car</li>
              <li>▸ Runs entirely in your browser. The only data collected here is the fake kind.</li>
            </ul>
            <div className="mt-6 flex flex-wrap gap-3">
              <button className="pw-btn pw-btn-solid" onClick={() => eng()?.startGame()}>
                ▶ start the week
              </button>
              <a className="pw-btn" href="/parkwise-report">
                read the report
              </a>
              <a className="pw-btn" href="/parkwise-demo">
                the api simulator
              </a>
            </div>
          </div>
        </div>
      )}

      {/* DAY NARRATIVE */}
      {ui.phase === "driving" && ui.day === day && (ui as any).__narrDone !== false && (
        <NarrativeGate key={day} day={day} />
      )}

      {/* PAY / EXTEND CHOICE */}
      {ui.phase === "paying" && (
        <div className="absolute inset-0 z-30 flex items-center justify-center bg-black/60 p-4">
          <div className="pw-card w-full p-7">
            <div className="pw-tag mb-3" style={{ color: "#35d07f" }}>
              parked · {daySpec.title}
            </div>
            {daySpec.payChoice ? (
              <>
                <h2 className="text-2xl uppercase" style={{ fontFamily: "Anton, sans-serif" }}>
                  How do you pay?
                </h2>
                <p className="mt-2 text-sm text-[#a39c8a]">₹120 for 3 hours. Two doors out of the same room.</p>
                <div className="mt-5 flex flex-col gap-3">
                  <button className="pw-btn pw-btn-solid text-left" onClick={() => eng()?.choosePay(false)}>
                    ▶ app payment — ₹120 · 2 taps · phone + UPI id logged
                  </button>
                  <button className="pw-btn text-left" onClick={() => eng()?.choosePay(true)}>
                    ▶ cash at kiosk — ₹120 · walk 90 m · plate still on camera
                  </button>
                </div>
              </>
            ) : (
              <>
                <h2 className="text-2xl uppercase" style={{ fontFamily: "Anton, sans-serif" }}>
                  The hearing runs long.
                </h2>
                <p className="mt-2 text-sm text-[#a39c8a]">Extend an hour in the app — honest. Or pull out and circle till it looks right. Both leave marks.</p>
                <div className="mt-5 flex flex-col gap-3">
                  <button className="pw-btn pw-btn-solid text-left" onClick={() => eng()?.chooseExtend(true)}>
                    ▶ extend +1 hr — the update event is logged
                  </button>
                  <button className="pw-btn text-left" onClick={() => eng()?.chooseExtend(false)}>
                    ▶ pull out &amp; circle — ANPR reads the plate each lap
                  </button>
                </div>
              </>
            )}
          </div>
        </div>
      )}

      {/* BUYER INTERSTITIAL */}
      {ui.phase === "buyer" && (
        <div className="absolute inset-0 z-30 flex items-center justify-center bg-black/70 p-4">
          <div className="pw-card w-full p-7">
            <div className="pw-tag mb-3" style={{ color: "#d95ce8" }}>
              downstream · day {day + 1}
            </div>
            <h2 className="text-2xl uppercase leading-tight" style={{ fontFamily: "Anton, sans-serif" }}>
              {daySpec.buyer.name}
            </h2>
            <div className="mt-1 font-mono text-[11px] uppercase tracking-widest" style={{ color: "#35d07f" }}>
              buys: {daySpec.buyer.buys}
            </div>
            <p className="mt-3 text-sm leading-relaxed text-[#a39c8a]">{daySpec.buyer.text}</p>
            <div className="mt-3 border-l-2 pl-3 text-xs" style={{ borderColor: "#ff5340", color: "#ff5340" }}>
              consequence · {daySpec.buyer.hit}
            </div>
            <button className="pw-btn pw-btn-solid mt-5" onClick={() => eng()?.nextDay()}>
              {day + 1 >= DAYS.length ? "▶ the receipt" : "▶ next day"}
            </button>
          </div>
        </div>
      )}

      {/* RECEIPT */}
      {ui.phase === "receipt" && (
        <div className="absolute inset-0 z-30 overflow-y-auto bg-[#0d0e0f]/95 p-4">
          <div className="pw-card mx-auto my-8 w-full max-w-xl p-8">
            <div className="pw-tag mb-3" style={{ color: "#ffc400" }}>
              week complete · the receipt you never see
            </div>
            <h2 className="text-4xl uppercase leading-none" style={{ fontFamily: "Anton, sans-serif" }}>
              {ui.points ?? 0} data points,<br />5 days, 1 curb
            </h2>
            <p className="mt-3 text-sm text-[#a39c8a]">
              Plate · geo · phone · instrument · arrival · departure · extensions · laps — assembled into a presence history and sold three times over. This week was fictional. The architecture is the one in the spec.
            </p>
            <div className="mt-4 grid grid-cols-2 gap-2 text-xs">
              <div className="border border-[#2c2a24] p-3">
                <div className="text-[#a39c8a] uppercase tracking-widest text-[10px]">your choices</div>
                <div className="mt-1">pay: {ui.cashChoice === null ? "n/a" : ui.cashChoice ? "cash kiosk" : "app"}</div>
                <div>plans: {ui.extendChoice === null ? "n/a" : ui.extendChoice ? "extended" : "circled"}</div>
              </div>
              <div className="border border-[#2c2a24] p-3">
                <div className="text-[#a39c8a] uppercase tracking-widest text-[10px]">anpr reads while driving</div>
                <div className="mt-1 text-2xl" style={{ color: "#ff5340" }}>{ui.anprReads ?? 0}</div>
              </div>
            </div>
            <div className="mt-5 flex flex-wrap gap-3">
              <button className="pw-btn pw-btn-solid" onClick={() => eng()?.reset()}>
                ▶ replay the week
              </button>
              <a className="pw-btn" href="/parkwise-report">the report</a>
              <a className="pw-btn" href="/parkwise-demo">harm pages</a>
            </div>
            <p className="mt-5 text-[10px] uppercase tracking-widest text-[#5a564d]">
              nothing you did in this game left your browser · kaarana · ಕಾರಣ
            </p>
          </div>
        </div>
      )}
    </div>
  );
}

/* narrative gate: shows day narrative until dismissed (local state) */
function NarrativeGate({ day }: { day: number }) {
  const [open, setOpen] = useState(true);
  const d = DAYS[day];
  if (!open) return null;
  return (
    <div className="absolute inset-0 z-20 flex items-center justify-center bg-black/50 p-4">
      <div className="pw-card w-full p-7">
        <div className="pw-tag mb-3" style={{ color: "#ffc400" }}>
          {d.title}
        </div>
        <p className="text-sm leading-relaxed text-[#e6e0d0]">{d.narrative}</p>
        <button className="pw-btn pw-btn-solid mt-5" onClick={() => setOpen(false)}>
          ▶ drive
        </button>
      </div>
    </div>
  );
}