// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { useMemo, useRef, useState, useEffect } from "react";
import { ChevronDown, ExternalLink, Car, MapPin, Building2, Search, AlertTriangle, Clock, ShieldX } from "lucide-react";

const CATEGORIES: Record<string, { label: string; color: string; bg: string }> = {
  gcc: { label: "GCC", color: "#4a9eda", bg: "rgba(74,158,218,0.14)" },
  cumta: { label: "CUMTA", color: "#4caf7d", bg: "rgba(76,175,125,0.14)" },
  mti: { label: "ParkWise / Moving Tech", color: "#f5b73d", bg: "rgba(245,183,61,0.14)" },
  osint: { label: "OSINT findings", color: "#e0504a", bg: "rgba(224,80,74,0.14)" },
};

interface Card {
  id: string;
  sort: string;
  date: string;
  cat: keyof typeof CATEGORIES;
  title: string;
  summary: string;
  sources: { label: string; url: string }[];
  flag?: string;
}

const CARDS: Card[] = [
  { id: "meters-2010", sort: "2010-01", date: "2010–11", cat: "gcc", title: "GCC's first parking meters fail", summary: "GCC installs parking meters (Royapettah etc.); they fail within a year — first lesson that hardware-only parking tech without enforcement design doesn't survive Chennai kerbs.", sources: [{ label: "The Hindu retrospective", url: "https://www.thehindu.com/news/cities/chennai/chennai-corporation-to-implement-city-wide-smart-parking-management/article70443852.ece" }] },
  { id: "google-2014", sort: "2014-01", date: "2014", cat: "gcc", title: "GCC–Google parking-lot search tie-up", summary: "GCC partners Google to show parking-lot availability in Adyar, Teynampet, Kodambakkam, Anna Nagar, Royapuram. Guidance-only; no pricing or enforcement.", sources: [{ label: "The Hindu retrospective", url: "https://www.thehindu.com/news/cities/chennai/chennai-corporation-to-implement-city-wide-smart-parking-management/article70443852.ece" }] },
  { id: "cumta-policy-2024", sort: "2024-02-26", date: "26 Feb 2024", cat: "cumta", title: "CUMTA submits draft parking policy for 5,904 sqkm CMA", summary: "CUMTA sends a draft parking policy for the entire Chennai Metropolitan Area (5,904 sqkm) to the TN Government for approval — the policy umbrella under which all later parking procurement sits.", sources: [{ label: "@UpdatesChennai, 26 Feb 2024", url: "https://x.com/UpdatesChennai/status/1761955599762280814" }] },
  { id: "ticketing-tender", sort: "2024-03-01", date: "1 Mar 2024", cat: "cumta", title: "CUMTA floats unified ticketing tender (context)", summary: "Tender 2024_CUMTA_432459_1 / CUMTA/9112/TICKETING/2024 (deadline 17 Apr 2024) — not parking, but the procurement that brings Moving Tech Innovations into CUMTA's orbit.", sources: [{ label: "Tender ref · UngalSoththu OSINT", url: "https://cashlessconsumer.zo.space/parkwise-timeline" }] },
  { id: "mti-award", sort: "2024-07-09", date: "9 Jul 2024", cat: "mti", title: "Moving Tech wins CUMTA ticketing bid (Chennai One)", summary: "CUMTA awards the common ticketing app tender to Moving Tech Innovation Pvt Ltd (Namma Yatri operator). Public, uncontested fact — the only proven CUMTA–MTI relationship. Parking is NOT in this award.", sources: [{ label: "@UpdatesChennai, 9 Jul 2024", url: "https://x.com/UpdatesChennai/status/1810530665663787035" }, { label: "@HereWorks detail", url: "https://x.com/HereWorks/status/1810673706131407181" }] },
  { id: "cumta-pretender", sort: "2024-11-09", date: "9 Nov 2024", cat: "cumta", title: "CUMTA pre-tender consultation: Smart Parking Management System", summary: "CUMTA publishes a pre-tender consultation doc for cluster-level smart parking (Anna Nagar Area-Level Parking Management Plan): surveillance cameras, POS with number-plate scans, local control centre, marshals, and a PPP concession covering hardware + O&M + revenue collection. Names NO vendor. Archived copy: UngalSoththu/osint/2024-11-cumta-smart-parking-pre-tender-consultation.pdf", sources: [{ label: "cumta.tn.gov.in PDF (retrieved 9 Sep 2026)", url: "https://cumta.tn.gov.in/upload/2024/11/09/1731130667-PTAGA.pdf" }, { label: "The Hindu Businessline", url: "https://www.thehindubusinessline.com/news/cumta-plans-to-implement-smart-parking-management-system-in-chennai/article68879165.ece" }] },
  { id: "scam-thread", sort: "2025-04-01", date: "Apr 2025", cat: "gcc", title: "'Mega Parking Scam' thread: collections despite failures", summary: "Journalist @omjasvinMD documents on-street fee collection continuing at Marina, Besant Nagar, T. Nagar after contract failures; revenue targets missed. Public trust baseline for any future digital operator.", sources: [{ label: "@omjasvinMD on X", url: "https://x.com/omjasvinMD" }] },
  { id: "texco-expiry", sort: "2025-07-20", date: "20 Jul 2025", cat: "gcc", title: "TEXCO collection contract expires; fees suspended", summary: "TN Ex-Servicemen Co-op's on-street fee collection (2022–25) expires; GCC suspends fees until re-tender — the kerb is officially unmanaged.", sources: [{ label: "LiveChennai press note", url: "https://www.livechennai.com" }] },
  { id: "rates-2025", sort: "2025-06-01", date: "Jun 2025", cat: "gcc", title: "Smart parking rates notified: ₹60/₹40/₹20 per hour", summary: "GCC notifies smart parking rates — ₹60/hr commercial vehicles, ₹40 cars, ₹20 two-wheelers; Anna Nagar and residential streets included.", sources: [{ label: "ThanthiTV", url: "https://www.thanthitv.com" }] },
  { id: "anna-september-promise", sort: "2025-09-01", date: "2025 · promised", cat: "cumta", title: "'Anna Nagar smart parking from September' — promised", summary: "CUMTA-flagged launch of the city's first smart parking solution in Anna Nagar 'from September' circulates. INFERENCE/CAVEAT: exact original date unverified; by Jul 2026 the pilot still hasn't been implemented (@reclaimchennai). A promise, not an event.", sources: [{ label: "Streets of Chennai post", url: "https://www.facebook.com/streetsofchennai/posts/-cumta-to-execute-citys-first-smart-parking-solution-in-anna-nagarfrom-september/1114549454036015" }], flag: "inference" },
  { id: "consultant-tender", sort: "2025-06-15", date: "2025", cat: "gcc", title: "GCC consultant tender for parking feasibility study — finalized", summary: "Tender 2025_CoC_528203_1: consultant for feasibility & demand study of a parking management and guidance system. Finalized; consultant unnamed in public mirrors.", sources: [{ label: "TN eProcurement", url: "https://tntenders.gov.in" }] },
  { id: "operator-tender", sort: "2025-12-15", date: "15 Dec 2025", cat: "gcc", title: "GCC operator tender: 2,100 bays, 26.43 km, Anna Nagar PPP", summary: "GCC calls the Anna Nagar PPP operator tender: 2,100 marked bays across 26.43 km, 5-year O&M; contractor gets towing powers, 1,300 cameras, 15 e-bikes, 120 bicycles, 110 body cams, ~300 staff (230 marshals); traffic police approve tows via app; live control-room monitoring. Winner NOT publicly announced as of 9 Sep 2026.", sources: [{ label: "TOI Chennai", url: "https://timesofindia.indiatimes.com/city/chennai" }, { label: "@omjasvinMD tender call", url: "https://x.com/omjasvinMD" }] },
  { id: "citywide-2025", sort: "2025-12-28", date: "28 Dec 2025", cat: "gcc", title: "GCC announces city-wide smart parking: 25+ locations", summary: "GCC announces smart parking across 25+ locations; Anna Nagar → T. Nagar first. Anchored to CUMTA's Comprehensive Mobility Plan target: regulated & priced parking across 36 high-demand areas by 2048; ~₹6 Cr/yr revenue possible per priced sq.km neighbourhood.", sources: [{ label: "The Hindu", url: "https://www.thehindu.com/news/cities/chennai/chennai-corporation-to-implement-city-wide-smart-parking-management/article70443852.ece" }] },
  { id: "twenty-areas", sort: "2026-03-01", date: "1 Mar 2026", cat: "gcc", title: "Rollout plan: 20 areas; Phase 1 named", summary: "GCC to roll out smart parking in 20 areas. Phase 1: Marina, Besant Nagar, Washermanpet, Nungambakkam, Anna Nagar — designated bays, QR/digital payment, cameras and data tools for violations.", sources: [{ label: "@UpdatesChennai, 1 Mar 2026", url: "https://x.com/UpdatesChennai/status/2028001651853037902" }] },
  { id: "chennai-one-live", sort: "2025-06-01", date: "2025 → 2026", cat: "mti", title: "ParkWise Chennai tenants go live on MTI platform", summary: "chennai.parkwise.moving.tech (City Manager app, /city/login) serves on Google Cloud (136.110.179.139 — WHOIS GOOGL-2, Google LLC; CORRECTED 9 Sep 2026 from an earlier erroneous 'TN govt IP' claim); parkwise.city (MTI-owned site, contact mohit@movingtech.com) lists chennai/blr/bhubaneswar tenants on AWS Mumbai; public ParkWise API (Beckn-style booking, Juspay payment links, Bhubaneswar example data). No public contract behind the Chennai tenant.", sources: [{ label: "UngalSoththu OSINT, 8 Sep 2026", url: "https://cashlessconsumer.zo.space/parkwise-timeline" }] },
  { id: "reclaimchennai-check", sort: "2026-07-26", date: "26 Jul 2026", cat: "cumta", title: "Status check: Anna Nagar pilot still not implemented", summary: "@reclaimchennai: CUMTA released its parking policy in 2025, aimed to pilot it in Anna Nagar 'long ago', yet to implement. CUMTA has taken planning/implementation authority from CMDA; should work with GCC + GCTP; 'nothing has happened yet'.", sources: [{ label: "@reclaimchennai, 26 Jul 2026", url: "https://x.com/reclaimchennai/status/2081432316849914262" }] },
  { id: "osint-verdict", sort: "2026-09-09", date: "8–9 Sep 2026", cat: "osint", title: "OSINT verdict: ParkWise–CUMTA parking link UNPROVEN", summary: "Systematic check: CUMTA pre-tender doc vendor-blind; the 18-Mar-2026 CUMTA tender is vehicle-hiring, not parking; 4,016-doc RTI corpus has zero hits for ParkWise/Moving Tech; no award, work order, MoU or press note names MTI for parking. The 'TN govt IP' anomaly cited on 8 Sep was a data error (see next card) — retracted, leaving zero govt-side hosting evidence. Verdict firms up: unconfirmed sales/pilot tenant. RTI to CUMTA + GCC is the definitive-proof path.", sources: [{ label: "UngalSoththu OSINT, 9 Sep 2026", url: "https://cashlessconsumer.zo.space/parkwise-timeline" }] },
  { id: "ip-correction", sort: "2026-09-09b", date: "9 Sep 2026", cat: "osint", title: "Correction: 'TN govt IP' claim retracted", summary: "WHOIS 136.110.179.139 → Google LLC (GOOGL-2); PTR → *.bc.googleusercontent.com; TLS cert → Google Trust Services for parkwise.moving.tech (SANs: chennai/bhubaneswar/admin/api). All five ParkWise hosts share this one GCP IP. The 8 Sep note's 'Govt of Tamil Nadu IP block' line was wrong and propagated to this page — corrected everywhere. Anyone can verify: whois 136.110.179.139; dig -x 136.110.179.139.", sources: [{ label: "ARIN/whois + RDAP record", url: "https://rdap.org/ip/136.110.179.139" }] },
];

const ORDERED = [...CARDS].sort((a, b) => a.sort.localeCompare(b.sort));
const CARD_BY_ID: Record<string, Card> = Object.fromEntries(CARDS.map((c) => [c.id, c]));

const OPEN_QUESTIONS = [
  "Who won GCC's Anna Nagar PPP operator tender (called 15 Dec 2025)? No public award as of 9 Sep 2026.",
  "Does any CUMTA/GCC document name Moving Tech Innovations or ParkWise for parking? None is public.",
  "What are Bhubaneswar BMC's ParkWise pilot terms — fee share, data clauses, exit? The benchmark Chennai should demand.",
  "CUMTA parking PMU delegation route: any consultant/PMU engagement naming MTI?",
];

const iconFor = (cat: string) => {
  switch (cat) {
    case "gcc": return <Building2 size={12} />;
    case "cumta": return <MapPin size={12} />;
    case "mti": return <Car size={12} />;
    default: return <Search size={12} />;
  }
};

export default function ParkwiseTimeline() {
  const [activeCat, setActiveCat] = useState<string>("all");
  const [openIds, setOpenIds] = useState<Set<string>>(new Set(["osint-verdict"]));
  const [highlightId, setHighlightId] = useState<string | null>(null);
  const cardRefs = useRef<Record<string, HTMLElement | null>>({});

  useEffect(() => {
    const hash = window.location.hash.replace("#", "");
    if (hash && CARD_BY_ID[hash]) {
      setHighlightId(hash);
      setOpenIds((p) => new Set([...p, hash]));
    }
  }, []);

  useEffect(() => {
    if (!highlightId) return;
    cardRefs.current[highlightId]?.scrollIntoView({ behavior: "smooth", block: "start" });
  }, [highlightId]);

  const visible = useMemo(() => (activeCat === "all" ? ORDERED : ORDERED.filter((c) => c.cat === activeCat)), [activeCat]);

  const counts = useMemo(() => {
    const c: Record<string, number> = { all: CARDS.length };
    for (const x of CARDS) c[x.cat] = (c[x.cat] || 0) + 1;
    return c;
  }, []);

  const toggle = (id: string) =>
    setOpenIds((prev) => {
      const n = new Set(prev);
      if (n.has(id)) n.delete(id); else n.add(id);
      return n;
    });

  return (
    <main className="min-h-screen" style={{ background: "#0b0e14", color: "#e7e9ee", fontFamily: "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif" }}>
      <div className="mx-auto max-w-4xl px-4 py-10 sm:px-6">
        <header className="mb-6">
          <div className="mb-3 flex flex-wrap items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.18em] text-[#8a93a3]">
            <span style={{ color: "#f5b73d" }}>உங்கள் சொத்து</span>
            <span>·</span>
            <span>UngalSoththu transit desk</span>
            <span>·</span>
            <span>Compiled 9 Sep 2026</span>
          </div>
          <h1 className="text-3xl font-bold leading-tight tracking-tight sm:text-4xl">
            Who runs Chennai's <span style={{ color: "#f5b73d" }}>kerbs?</span>
          </h1>
          <p className="mt-3 max-w-3xl text-sm leading-relaxed text-[#aab2c0]">
            Three tracks on one clock: GCC's operator tenders, CUMTA's policy-and-procurement push,
            and ParkWise (Moving Tech Innovations) building live Chennai infrastructure with{" "}
            <strong style={{ color: "#e7e9ee" }}>no public contract</strong>. Every card links to the
            underlying document or report.
          </p>
          <div className="mt-4 flex flex-wrap gap-2 text-[11px] text-[#8a93a3]">
            <span className="rounded border border-[#232c3d] bg-[#10151f] px-2 py-1">2,100 bays · Anna Nagar PPP</span>
            <span className="rounded border border-[#232c3d] bg-[#10151f] px-2 py-1">36 high-demand areas by 2048 (CMP)</span>
            <span className="rounded border border-[#232c3d] bg-[#10151f] px-2 py-1">₹60/₹40/₹20 per hr notified rates</span>
            <span className="rounded border border-[#232c3d] bg-[#10151f] px-2 py-1">0 public parking contracts naming MTI</span>
          </div>
        </header>

        <section className="mb-6 rounded-xl border p-4" style={{ borderColor: "#e0504a55", background: "rgba(224,80,74,0.07)" }}>
          <div className="flex items-start gap-2.5">
            <AlertTriangle size={16} className="mt-0.5 shrink-0" style={{ color: "#e0504a" }} />
            <p className="text-[13px] leading-relaxed text-[#d8dbe2]">
              <strong style={{ color: "#f1f3f7" }}>The verdict (9 Sep 2026, corrected):</strong> ParkWise ↔ Moving Tech is proven (own product).
              Moving Tech ↔ CUMTA is proven — for <em>ticketing</em> (Chennai One, Jul 2024).
              ParkWise ↔ CUMTA for <strong style={{ color: "#f1f3f7" }}>parking is unproven</strong> — no award, work order, MoU,
              or RTI reply names them. A live "chennai" tenant exists at chennai.parkwise.moving.tech, but it sits on ordinary
              Google Cloud (WHOIS: Google LLC — 9 Sep correction; an earlier "govt IP" note here was wrong and is retracted),
              leaving zero govt-side hosting evidence. Treat "ParkWise runs Chennai parking" as false until a contract surfaces.
            </p>
          </div>
        </section>

        <section className="mb-6 rounded-xl border border-[#232c3d] bg-[#0d1119]/95 p-4">
          <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
            <span className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#8a93a3]">
              Visual timeline — {ORDERED.length} events
            </span>
            <span className="text-[10px] text-[#6d7688]">Click a point to jump to its card · scroll ⟷</span>
          </div>
          <div className="overflow-x-auto">
            <div className="relative flex min-w-[1400px] items-start">
              <div className="absolute left-0 right-0 top-[6px] h-[2px] rounded-full bg-gradient-to-r from-[#1f2837] via-[#2c3850] to-[#1f2837]" />
              {ORDERED.map((card) => {
                const meta = CATEGORIES[card.cat];
                const active = highlightId === card.id;
                return (
                  <button
                    key={card.id}
                    onClick={() => { setActiveCat("all"); setHighlightId(card.id); setOpenIds((p) => new Set([...p, card.id])); }}
                    title={`${card.date} — ${card.title}`}
                    className="group relative flex w-[80px] shrink-0 flex-col items-center px-0.5 outline-none"
                  >
                    <span
                      className="relative z-10 h-3.5 w-3.5 rounded-full border-2 transition-transform duration-150 group-hover:scale-125"
                      style={{ background: active ? meta.color : "#0d1119", borderColor: meta.color, boxShadow: active ? `0 0 0 4px ${meta.color}40` : undefined }}
                    />
                    <span className="mt-1.5 text-[10px] font-bold tracking-wide" style={{ color: meta.color }}>{card.date.replace(" · promised", "")}</span>
                    <span className="mt-0.5 line-clamp-2 text-center text-[9px] leading-[1.25] text-[#8a93a3] transition group-hover:text-[#e7e9ee]">
                      {card.title.length > 42 ? card.title.slice(0, 40) + "…" : card.title}
                    </span>
                  </button>
                );
              })}
            </div>
          </div>
        </section>

        <div className="sticky top-2 z-10 mb-6 rounded-xl border border-[#232c3d] bg-[#0d1119]/95 p-3 backdrop-blur">
          <div className="flex flex-wrap gap-1.5">
            <button
              onClick={() => setActiveCat("all")}
              className="rounded-full border px-3 py-1 text-[12px] font-medium transition"
              style={activeCat === "all"
                ? { background: "#e7e9ee", color: "#0b0e14", borderColor: "#e7e9ee" }
                : { background: "transparent", color: "#aab2c0", borderColor: "#2a3550" }}
            >
              All <span className="opacity-60">({counts.all})</span>
            </button>
            {Object.keys(CATEGORIES).map((k) => {
              const meta = CATEGORIES[k];
              const active = activeCat === k;
              return (
                <button
                  key={k}
                  onClick={() => setActiveCat(active ? "all" : k)}
                  className="rounded-full border px-3 py-1 text-[12px] font-medium transition"
                  style={{
                    background: active ? meta.color : meta.bg,
                    color: active ? "#0b0e14" : meta.color,
                    borderColor: active ? meta.color : meta.color + "66",
                  }}
                >
                  {meta.label} <span className="opacity-70">({counts[k] || 0})</span>
                </button>
              );
            })}
          </div>
        </div>

        <div className="space-y-3">
          {visible.map((card) => {
            const meta = CATEGORIES[card.cat];
            const open = openIds.has(card.id);
            return (
              <article
                key={card.id}
                ref={(el) => { cardRefs.current[card.id] = el; }}
                className={`scroll-mt-32 rounded-xl border transition ${
                  highlightId === card.id ? "border-[#f5b73d] bg-[#121722] ring-2 ring-[#f5b73d]/60" : "border-[#1f2837] bg-[#121722] hover:border-[#2c3850]"
                }`}
              >
                <button onClick={() => toggle(card.id)} className="flex w-full items-start gap-3 px-4 pt-4 pb-2 text-left sm:gap-4 sm:px-5">
                  <div className="mt-0.5 hidden w-24 shrink-0 text-right sm:block">
                    <span className="text-[12px] font-semibold text-[#aab2c0]">{card.date}</span>
                  </div>
                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="rounded px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wider" style={{ color: meta.color, background: meta.bg }}>
                        {iconFor(card.cat)} {meta.label}
                      </span>
                      {card.flag === "inference" && (
                        <span className="rounded bg-[#e0504a26] px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wider text-[#e0504a]">inference</span>
                      )}
                      <span className="text-[11px] text-[#8a93a3] sm:hidden">{card.date}</span>
                    </div>
                    <h2 className="mt-1.5 text-[15px] font-semibold leading-snug text-[#f1f3f7]">{card.title}</h2>
                    <p className={`mt-1.5 text-[13px] leading-relaxed text-[#aab2c0] ${open ? "" : "line-clamp-2"}`}>{card.summary}</p>
                  </div>
                  <ChevronDown size={16} className={`mt-1 shrink-0 text-[#8a93a3] transition-transform ${open ? "rotate-180" : ""}`} />
                </button>
                <div className="px-4 pb-4 sm:px-5 sm:pl-36">
                  <div className="flex flex-wrap gap-x-4 gap-y-1 border-t border-[#1f2837] pt-2.5">
                    {card.sources.map((s, i) => (
                      <a key={i} href={s.url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-[12px] text-[#6fa8dc] transition hover:text-[#9cc7ee]">
                        <ExternalLink size={11} /> {s.label}
                      </a>
                    ))}
                  </div>
                </div>
              </article>
            );
          })}
        </div>

        <section className="mt-8 rounded-xl border border-[#232c3d] bg-[#0d1119]/95 p-4">
          <div className="mb-3 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.16em] text-[#8a93a3]">
            <Clock size={13} /> Open questions — what would settle this
          </div>
          <ol className="list-decimal space-y-2 pl-5 text-[13px] leading-relaxed text-[#aab2c0]">
            {OPEN_QUESTIONS.map((q, i) => (
              <li key={i}>{q}</li>
            ))}
          </ol>
          <p className="mt-3 text-[12px] leading-relaxed text-[#6d7688]">
            RTI asks (file-ready): GCC PIO — Anna Nagar PPP RFP, bidder names, evaluation, L1, work order, any MoU with
            "Moving Tech Innovations"/"ParkWise" 2023–26. CUMTA PIO — parking study deliverables (CUMTA/9112 series), any
            pilot/LoI/MoU with MTI, data-sharing agreements between CUMTA platforms and any parking vendor.
          </p>
        </section>

        <footer className="mt-8 border-t border-[#1f2837] pt-4 text-[11px] leading-relaxed text-[#6d7688]">
          <p>
            Compiled 9 Sep 2026 by the UngalSoththu transit desk (பொதுப் போக்குவரத்து is உங்கள் சொத்து) from primary documents
            (cumta.tn.gov.in pre-tender consultation, TN eProcurement entries, ParkWise API spec, DNS/CT-log recon) and reporting
            by The Hindu, The Hindu Businessline, TOI, ThanthiTV, LiveChennai, plus field posts by @omjasvinMD, @UpdatesChennai
            and @reclaimchennai. Items marked "inference" are unverified date attributions. Parking policy data: public record only.
          </p>
        </footer>
      </div>
    </main>
  );
}
