// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { readFileSync } from "node:fs";
import type { Context } from "hono";

const MD_PATH =
  "/home/workspace/Kaarana/research/urban/2026-09-09-pay-and-display-counter-narrative.md";

export default (c: Context) => {
  try {
    const md = readFileSync(MD_PATH, "utf8");
    return c.json({
      title: "Pay & Display: A Counter-Narrative on Smart Parking",
      markdown: md,
    });
  } catch (e) {
    return c.json({ error: "report source not found" }, 404);
  }
}