// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";
import { readFileSync, existsSync } from "node:fs";

const BASE = "/home/workspace/Kaarana/data/parkwise";

function safeSlug(raw: string): string | null {
  const m = raw.match(/^[a-z0-9-]{1,40}$/);
  return m ? raw : null;
}

export default (c: Context) => {
  const slug = safeSlug(c.req.param("slug"));
  if (!slug) return c.text("Not found", 404);

  try {
    if (slug === "spec") {
      const p = `${BASE}/parkwise-public-api-openapi.json`;
      if (!existsSync(p)) return c.text("Spec not found", 404);
      return c.body(readFileSync(p, "utf-8"), 200, {
        "Content-Type": "application/json; charset=utf-8",
      });
    }

    const p = `${BASE}/harms/${slug}.html`;
    if (!existsSync(p)) return c.text("Not found", 404);
    return c.html(readFileSync(p, "utf-8"));
  } catch (e) {
    return c.text("Failed to load ParkWise page: " + String(e), 500);
  }
}