// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";
import { readFileSync, existsSync } from "node:fs";

const SRC = "/home/workspace/Kaarana/data/parkwise/demo.html";

export default (c: Context) => {
  try {
    if (!existsSync(SRC)) {
      return c.text("demo.html not found in workspace", 404);
    }
    return c.html(readFileSync(SRC, "utf-8"));
  } catch (e) {
    return c.text("Failed to load ParkWise demo: " + String(e), 500);
  }
}